
name: reelon_app
description: ReelOn style Instagram based reels & casting app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  video_player: ^2.8.1

flutter:
  uses-material-design: true
